# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_script:
    name: Run Script
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run script
      run: |
        python3 script.py

  update_submodule:
    name: Update Submodule
    needs: [run_script]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout setup
      uses: actions/checkout@v2
    - name: Commit changes
      run: |
        cd buildfarm-tools-test/
        git add mytext.txt
        git commit -m "Update mytext.txt"
        
  update_parent:
    name: Update parent
    needs: [update_submodule]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Git Sumbodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive
