name: Update Submodule

on:
  workflow_dispatch:

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Update Submodule
        run: |
          python3 script.py
          
          cd buildfarm-tools-test
          git config user.name "Crola1702"
          git config user.email "j.arroyo@uniandes.edu.co"
          git add .
          git commit -m "Update submodule"
          git push origin HEAD:main

      - name: Commit and Push Main Repository
        run: |
          # Commit the submodule reference update
          git add buildfarm-tools-test
          git commit -m "Update submodule reference"

          # Push changes to the main repository
          git push origin main
