name: Update Public Database

on:
  workflow_dispatch:

jobs:
  update-public-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Clone buildfarm-tools-test
        run: |
          git clone --depth 1 https://@github.com/Crola1702/buildfarm-tools-test/
      - name: Update Public Database
        run: |
          python3 script.py
      - name: Commit and push changes
        run: |
          cd buildfarm-tools-test
          git config --global user.name 'Crola1702'
          git config --global user.email 'j.arroyo@uniandes.edu.co'
          git add .
          git commit -m "Update Public Database"
          git push https://${{ secrets.GH_TOKEN }}@github.com/Crola1702/buildfarm-tools-test.git

