name: Update Public Database

on:
  workflow_dispatch:

jobs:
  update-public-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v2
      - name: Checkout Public Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: Crola1702/buildfarm-tools-test
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Check current repository
        run: |
          ls
      - name: Check public repository
        run: |
          ls ../buildfarm-tools-test
      - name: Update Public Database
        run: |
          python3 script.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
